repository_type: pipeline
lint:
  files_unchanged:
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - pyproject.toml
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
  multiqc_config: false
