name: nf-core AWS full size tests
# This workflow is triggered on published releases.
# It can be additionally triggered manually with GitHub actions workflow dispatch button.
# It runs the -profile 'test_full' on AWS batch

on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  run-tower:
    name: Run AWS AlphaFold2 full monomer tests
    if: github.repository == 'nf-core/proteinfold'
    runs-on: ubuntu-latest
    # Do a full-scale run on each of the mode
    strategy:
      matrix:
        mode:
          [
            "_alphafold2_standard",
            "_alphafold2_split",
            "_alphafold2_multimer",
            "_colabfold_local",
            "_colabfold_webserver",
            "_colabfold_multimer",
            "_esmfold",
            "_esmfold_multimer",
          ]
    steps:
      - name: Launch workflow via tower
        uses: nf-core/tower-action@v3
        # TODO nf-core: You can customise AWS full pipeline tests as required
        # Add full size test data (but still relatively small datasets for few samples)
        # on the `test_full.config` test runs with only one set of parameters
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/proteinfold/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/proteinfold/results-${{ github.sha }}/mode_${{ matrix.mode }}"
            }
          profiles: test_full_${{ matrix.mode }},aws_tower
      - uses: actions/upload-artifact@v3
        with:
          name: Tower debug log file
          path: tower_action_*.log
